version: 2
models:
  - name: stg_weather_metrics
    description: "View de staging com colunas renomeadas e padronizadas"
    columns:
      - name: id
        tests: [not_null, unique]
      - name: city
        tests: [not_null]
      - name: country
        tests: [not_null]   
      - name: collected_at
        tests: [not_null]
      - name: temperature
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -20
              max_value: 60
      - name: humidity
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: wind_speed
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 200